[build]
  base = "frontend"           # Set the base directory to 'frontend' where Next.js resides.
  publish = "frontend/.next"   # Publish the built files from the .next folder inside 'frontend'.
  command = "npm run build"    # Command to build the Next.js app.

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Ensure Next.js works with Netlify properly.
