[build]
  base = "frontend"           # Points to the 'frontend' folder where Next.js resides.
  publish = ".next"            # Set to `.next` (relative to the base directory).
  command = "npm run build"    # Builds the Next.js app.

[[plugins]]
  package = "@netlify/plugin-nextjs"
